import { ConstructorOptions } from "audiomotion-analyzer";

export const AUDIO_MOTION_ANALYZER_SETTINGS: ConstructorOptions =
//{
//  "alphaBars": true,
//  "ansiBands": false,
//  "barSpace": 0.25,
//  "bgAlpha": 0.7,
//  "channelLayout": "single",
//  "colorMode": "bar-level",
//  "fadePeaks": false,
//  "fftSize": 1024,
//  "fillAlpha": "1",
//  "frequencyScale": "log",
//  "gradient": "prism",
//  "gravity": 14.7,
//  "ledBars": false,
//  "linearAmplitude": true,
//  "linearBoost": 3.6,
//  "lineWidth": 1.5,
//  "loRes": false,
//  "lumiBars": false,
//  "maxDecibels": 0,
//  "maxFPS": 0,
//  "maxFreq": 8000,
//  "minDecibels": -110,
//  "minFreq": 10,
//  "mirror": 0,
//  "mode": 2,
//  "noteLabels": false,
//  "outlineBars": false,
//  "overlay": false,
//  "peakFadeTime": 750,
//  "peakHoldTime": 500,
//  "peakLine": false,
//  "radial": false,
//  "radialInvert": false,
//  "radius": 0.3,
//  "reflexAlpha": 1,
//  "reflexBright": 1,
//  "reflexFit": true,
//  "reflexRatio": 0.5,
//  "roundBars": false,
//  "showBgColor": false,
//  "showFPS": false,
//  "showPeaks": true,
//  "showScaleX": false,
//  "showScaleY": false,
//  "smoothing": 0.3,
//  "spinSpeed": 0,
//  "splitGradient": false,
//  "trueLeds": false,
//  "useCanvas": true,
//  "volume": 1,
//  "weightingFilter": "C"
//}









//{
//  "alphaBars": false,
//  "ansiBands": false,
//  "barSpace": 0.9,
//  "bgAlpha": 0.7,
//  "channelLayout": "single",
//  "colorMode": "gradient",
//  "fadePeaks": false,
//  "fftSize": 1024,
//  "fillAlpha": "1",
//  "frequencyScale": "mel",
//  "gradient": "rainbow",
//  "gravity": 12.5,
//  "ledBars": false,
//  "linearAmplitude": true,
//  "linearBoost": 4,
//  "lineWidth": 4,
//  "loRes": false,
//  "lumiBars": false,
//  "maxDecibels": -20,
//  "maxFPS": 0,
//  "maxFreq": 22000,
//  "minDecibels": -75,
//  "minFreq": 16,
//  "mirror": -1,
//  "mode": 10,
//  "noteLabels": false,
//  "outlineBars": false,
//  "overlay": false,
//  "peakFadeTime": 750,
//  "peakHoldTime": 500,
//  "peakLine": false,
//  "radial": false,
//  "radialInvert": false,
//  "radius": 0.3,
//  "reflexAlpha": "1",
//  "reflexBright": 1,
//  "reflexFit": true,
//  "reflexRatio": 0.5,
//  "roundBars": false,
//  "showBgColor": false,
//  "showFPS": false,
//  "showPeaks": false,
//  "showScaleX": false,
//  "showScaleY": false,
//  "smoothing": 0,
//  "spinSpeed": 0,
//  "splitGradient": false,
//  "trueLeds": false,
//  "useCanvas": true,
//  "volume": 1,
//  "weightingFilter": "468"
//}








//{
//  "alphaBars": false,
//  "ansiBands": false,
//  "barSpace": 0.5,
//  "bgAlpha": 0.7,
//  "channelLayout": "single",
//  "colorMode": "gradient",
//  "fadePeaks": false,
//  "fftSize": 2048,
//  "fillAlpha": "1",
//  "frequencyScale": "log",
//  "gradientLeft": "orangered",
//  "gradientRight": "classic",
//  "gravity": 12.5,
//  "ledBars": false,
//  "linearAmplitude": false,
//  "linearBoost": 2.2,
//  "lineWidth": 0,
//  "loRes": false,
//  "lumiBars": false,
//  "maxDecibels": -15,
//  "maxFPS": 0,
//  "maxFreq": 22050,
//  "minDecibels": -75,
//  "minFreq": 16,
//  "mirror": 0,
//  "mode": 10,
//  "noteLabels": false,
//  "outlineBars": false,
//  "overlay": false,
//  "peakFadeTime": 750,
//  "peakHoldTime": 500,
//  "peakLine": false,
//  "radial": false,
//  "radialInvert": false,
//  "radius": 0.3,
//  "reflexAlpha": "1",
//  "reflexBright": 1,
//  "reflexFit": true,
//  "reflexRatio": 0.5,
//  "roundBars": false,
//  "showBgColor": false,
//  "showFPS": false,
//  "showPeaks": false,
//  "showScaleX": false,
//  "showScaleY": false,
//  "smoothing": 0.5,
//  "spinSpeed": 0,
//  "splitGradient": false,
//  "trueLeds": false,
//  "useCanvas": true,
//  "volume": 1,
//  "weightingFilter": ""
//}









//{
//  "alphaBars": false,
//  "ansiBands": false,
//  "barSpace": 0.5,
//  "bgAlpha": 0.7,
//  "channelLayout": "single",
//  "colorMode": "gradient",
//  "fadePeaks": false,
//  "fftSize": 8192,
//  "fillAlpha": 1,
//  "frequencyScale": "log",
//  "gradientLeft": "orangered",
//  "gradientRight": "classic",
//  "gravity": 3.8,
//  "ledBars": false,
//  "linearAmplitude": false,
//  "linearBoost": 2.2,
//  "lineWidth": 0,
//  "loRes": false,
//  "lumiBars": false,
//  "maxDecibels": -10,
//  "maxFPS": 0,
//  "maxFreq": 22000,
//  "minDecibels": -70,
//  "minFreq": 20,
//  "mirror": 0,
//  "mode": 10,
//  "noteLabels": false,
//  "outlineBars": false,
//  "overlay": false,
//  "peakFadeTime": 750,
//  "peakHoldTime": 500,
//  "peakLine": false,
//  "radial": false,
//  "radialInvert": false,
//  "radius": 0.3,
//  "reflexAlpha": 1,
//  "reflexBright": 1,
//  "reflexFit": true,
//  "reflexRatio": 0.5,
//  "roundBars": false,
//  "showBgColor": false,
//  "showFPS": false,
//  "showPeaks": false,
//  "showScaleX": false,
//  "showScaleY": false,
//  "smoothing": 0.6,
//  "spinSpeed": 0,
//  "splitGradient": false,
//  "trueLeds": false,
//  "useCanvas": true,
//  "volume": 1,
//  "weightingFilter": ""
//}













{
  "alphaBars": false,
  "ansiBands": false,
  "barSpace": 0.5,
  "bgAlpha": 0.7,
  "channelLayout": "single",
  "colorMode": "gradient",
  "fadePeaks": false,
  "fftSize": 16384,
  "fillAlpha": 1,
  "frequencyScale": "log",
  "gradient": "classic",
  "gravity": 3.8,
  "ledBars": true,
  "linearAmplitude": false,
  "linearBoost": 1,
  "lineWidth": 0,
  "loRes": false,
  "lumiBars": false,
  "maxDecibels": -20,
  "maxFPS": 30,
  "maxFreq": 22000,
  "minDecibels": -85,
  "minFreq": 20,
  "mirror": 0,
  "mode": 6,
  "noteLabels": false,
  "outlineBars": false,
  "overlay": false,
  "peakFadeTime": 750,
  "peakHoldTime": 500,
  "peakLine": false,
  "radial": false,
  "radialInvert": false,
  "radius": 0.3,
  "reflexAlpha": 1,
  "reflexBright": 1,
  "reflexFit": true,
  "reflexRatio": 0.5,
  "roundBars": false,
  "showBgColor": false,
  "showFPS": false,
  "showPeaks": false,
  "showScaleX": false,
  "showScaleY": false,
  "smoothing": 0.4,
  "spinSpeed": 0,
  "splitGradient": false,
  "trueLeds": false,
  "useCanvas": true,
  "volume": 1,
  "weightingFilter": ""
}










//{
//  "alphaBars": false,
//  "ansiBands": false,
//  "barSpace": 0.1,
//  "bgAlpha": 0.7,
//  "channelLayout": "single",
//  "colorMode": "bar-level",
//  "fadePeaks": false,
//  "fftSize": 4096,
//  "fillAlpha": 0.25,
//  "frequencyScale": "mel",
//  "gradientLeft": "steelblue",
//  "gradientRight": "orangered",
//  "gravity": 4.3,
//  "ledBars": true,
//  "linearAmplitude": true,
//  "linearBoost": 2,
//  "lineWidth": 1.5,
//  "loRes": false,
//  "lumiBars": false,
//  "maxDecibels": -20,
//  "maxFPS": 60,
//  "maxFreq": 20000,
//  "minDecibels": -100,
//  "minFreq": 20,
//  "mirror": -1,
//  "mode": 7,
//  "noteLabels": false,
//  "outlineBars": false,
//  "overlay": false,
//  "peakFadeTime": 900,
//  "peakHoldTime": 100,
//  "peakLine": false,
//  "radial": false,
//  "radialInvert": false,
//  "radius": 0.3,
//  "reflexAlpha": "1",
//  "reflexBright": "1",
//  "reflexFit": false,
//  "reflexRatio": 0.5,
//  "roundBars": false,
//  "showBgColor": false,
//  "showFPS": false,
//  "showPeaks": true,
//  "showScaleX": false,
//  "showScaleY": false,
//  "smoothing": 0.7,
//  "spinSpeed": 0,
//  "splitGradient": false,
//  "trueLeds": false,
//  "useCanvas": true,
//  "volume": 1,
//  "weightingFilter": ""
//}











//{
//  "alphaBars": false,
//  "ansiBands": false,
//  "barSpace": 0.1,
//  "bgAlpha": 0.7,
//  "channelLayout": "single",
//  "colorMode": "gradient",
//  "fadePeaks": false,
//  "fftSize": 4096,
//  "fillAlpha": "0.1",
//  "frequencyScale": "bark",
//  "gradient": "orangered",
//  "gravity": 2.8,
//  "ledBars": false,
//  "linearAmplitude": true,
//  "linearBoost": 1.8,
//  "lineWidth": 4,
//  "loRes": false,
//  "lumiBars": false,
//  "maxDecibels": -35,
//  "maxFPS": 60,
//  "maxFreq": 8000,
//  "minDecibels": -100,
//  "minFreq": 1000,
//  "mirror": -1,
//  "mode": 0,
//  "noteLabels": false,
//  "outlineBars": false,
//  "overlay": false,
//  "peakFadeTime": 200,
//  "peakHoldTime": 250,
//  "peakLine": false,
//  "radial": false,
//  "radialInvert": false,
//  "radius": 0.3,
//  "reflexAlpha": "1",
//  "reflexBright": "1",
//  "reflexFit": true,
//  "reflexRatio": 0.5,
//  "roundBars": false,
//  "showBgColor": false,
//  "showFPS": false,
//  "showPeaks": true,
//  "showScaleX": false,
//  "showScaleY": false,
//  "smoothing": 0,
//  "spinSpeed": 1,
//  "splitGradient": false,
//  "trueLeds": false,
//  "useCanvas": true,
//  "volume": 1,
//  "weightingFilter": "468"
//}